import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(
    new Request("http://localhost/", { headers: { accept: "text/html" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

test("포커 랜덤 디펜스의 핵심 게임 화면을 렌더링한다", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);

  const html = await response.text();
  assert.match(html, /<title>포커 랜덤 디펜스<\/title>/);
  assert.match(html, /WAVE/);
  assert.match(html, /내 유닛/);
  assert.match(html, /전체 공격력/);
  assert.match(html, /전체 공격속도/);
  assert.match(html, /족보 확정 &amp; 소환/);
});

test("7장 손패와 모바일 전투 조작을 제공한다", async () => {
  const html = await (await render()).text();
  const pokerCards = html.match(/class="[^"]*poker-card[^"]*"/g) ?? [];
  assert.equal(pokerCards.length, 7);
  assert.match(html, /선택 카드 교체/);
  assert.match(html, /전체 손패 교체/);
  assert.match(html, /웨이브 시작/);
  assert.match(html, /52 \+ 2J/);
  assert.match(html, /200/);
});

test("현재 전투·연출·모바일 규칙을 고정한다", async () => {
  const [page, css, audio, i18n] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
    readFile(new URL("../app/game-audio.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/i18n.ts", import.meta.url), "utf8"),
  ]);

  assert.match(page, /POKER RANDOM DEFENSE/);
  assert.doesNotMatch(page, /FORTRESS OF FATE/);
  assert.match(page, /elf:\s*"\\uAD81\\uC218"/);
  assert.match(page, /const RANGE_PER_CELL = 100 \/ 12/);
  assert.match(page, /const PRIEST_BUFF_RANGE = RANGE_PER_CELL \* 2/);
  assert.match(page, /straight:\s*\{[\s\S]*?base:\s*\[15\.6,\s*RANGE_PER_CELL \* 5,\s*\.5\]/);
  assert.match(page, /flush:\s*\{[\s\S]*?base:\s*\[17\.28,\s*RANGE_PER_CELL \* 2,\s*\.5\]/);
  assert.match(page, /fourKind:\s*\{[\s\S]*?base:\s*\[43\.5,\s*RANGE_PER_CELL \* 6,\s*1\.15\]/);
  assert.match(page, /royalFlush:\s*\{[\s\S]*?base:\s*\[187\.5,\s*100,\s*\.82\]/);
  assert.doesNotMatch(page, /rangeMult/);
  assert.match(page, /<= PRIEST_BUFF_RANGE/);
  assert.match(page, /markExpirations\.set\(target\.id,\s*now \+ 2000\)/);
  assert.match(page, /critical = Math\.random\(\) < \.5/);
  assert.match(page, /baseDamage \* \(critical \? 5 : 1\)/);
  assert.match(page, /case "straight": return "장거리 \+ 치명타 50% · 피해 5배 \+ 보스 100% 추가 피해"/);
  assert.match(page, /case "pair": return "속사 \+ 2초간 받는 피해 20% 표식"/);
  assert.match(page, /tower\.category === "pair"[^}]+markExpirations\.set\(target\.id, now \+ 2000\)/);
  assert.match(page, /markedMultiplier = markExpirations\.has\(id\) \? 1\.2 : 1/);
  assert.match(page, /baseDamage \* \(critical \? 5 : 1\) \* \(target\.boss \? 2 : 1\)/);
  assert.match(page, /baseDamage \* \(target\.boss \? 1\.5 : 1\)/);
  assert.doesNotMatch(page, /장거리 \+ 피해 20% 표식/);
  assert.match(page, /const MAX_ATTACK_SPEED_LEVEL = 30/);
  assert.match(page, /attackSpeedLevel >= MAX_ATTACK_SPEED_LEVEL/);
  assert.match(page, /전체 공격속도는 LV\.30이 최대입니다/);
  assert.match(page, /lastAttackAtRef = useRef<Map<string, number>>/);
  assert.match(page, /attackInterval = 500 \/ Math\.max/);
  assert.match(page, /towerId: tower\.id,\s*expiresAt: now \+ 320/);
  assert.match(page, /attackFx\.some\(fx => fx\.towerId === tower\.id\) \? "attacking"/);
  assert.match(page, /fixedUtility = best\.category === "flush" \|\| best\.category === "fullHouse"/);
  assert.match(page, /triple:\s*\{[\s\S]*?base:\s*\[15\.6,\s*RANGE_PER_CELL \* 5,\s*\.6\]/);
  assert.match(page, /flush:\s*\{[\s\S]*?base:\s*\[17\.28,\s*RANGE_PER_CELL \* 2,\s*\.5\]/);
  assert.match(page, /fullHouse:\s*\{[\s\S]*?base:\s*\[21\.92,\s*RANGE_PER_CELL \* 4,\s*\.65\]/);
  assert.match(page, /className="inventory-selection"/);
  assert.match(page, /\{copy\.sell\} \{sellValue\(selectedInventoryUnit\)\}G/);
  assert.match(page, /className="field-unit-actions"/);
  assert.match(page, /function sellTower\(\)/);
  assert.match(page, /className="hand-result summon-preview"/);
  assert.match(page, /className=\{`unit-dock/);
  assert.match(page, /className="summon-stats"/);
  assert.match(page, /setHand\(dealHand\(0\)\)/);
  assert.match(page, /initialDealRef\.current = true; setHand\(dealHand\(0\)\)/);
  assert.match(page, /const PIP_POSITIONS/);
  assert.match(page, /function cardCenter\(card: Card\)/);
  assert.match(page, /sprites\/royal-jester\.png/);
  assert.match(page, /sprites\/cards\/\$\{filename\}\.png/);
  assert.match(page, /court-\$\{card\.suit\}/);
  assert.match(page, /className="card-center"/);
  assert.match(page, /const cost = selected\.length \* 5/);
  assert.match(page, /setSelected\(selectedIndexes\.map\(index => next\[index\]\.id\)\)/);
  assert.match(page, /function redrawAll\(\)/);
  assert.match(page, /selectedRerollsLeft <= 0/);
  assert.match(page, /setSelectedRerollsLeft\(v => v - 1\)/);
  assert.match(page, /setSelectedRerollsLeft\(3\)/);
  assert.match(page, /setHand\(dealHand\(saintPity\)\);\s*setSelectedRerollsLeft\(3\);\s*setCooldown\(0\)/);
  assert.match(page, /wave === 1 && spawned === 0 \? baseCopy\.begin : baseCopy\.start/);
  assert.match(page, /if \(!running \|\| gameOver \|\| spawned >= waveTarget/);
  assert.match(page, /setGold\(v => v - 3\); setHand\(dealHand\(saintPity\)\)/);
  assert.match(page, /radius: 10,\s*expiresAt: now \+ 2000,[^}]+slow: \.5/);
  assert.match(page, /cursedHits\.add\(enemy\.id\)/);
  assert.match(page, /fourKind:[^\n]+base: \[43\.5, RANGE_PER_CELL \* 6, 1\.15\]/);
  assert.match(page, /straightFlush:[^\n]+base: \[85\.5, RANGE_PER_CELL \* 6, 1\.25\]/);
  assert.match(page, /royalFlush:[^\n]+base: \[187\.5, 100, \.82\]/);
  assert.match(page, /setGold\(v => v \+ 2000\)/);
  assert.match(page, /spawnInterval: 432, minSpawnInterval: 312/);
  assert.match(page, /isPriestBuffed/);
  assert.match(page, /사제 버프 적용 중/);
  assert.match(page, /placeHint: selectedPlaced \? roleDescription\(selectedPlaced, locale\) : baseCopy\.placeHint/);
  assert.match(page, /공격 사거리 4칸 · 버프 범위 2칸 내 아군 공격 \+20% · 속도 \+20%/);
  assert.match(css, /\.alchemy-pool\s*\{/);
  assert.doesNotMatch(css, /\.tower-slot\.alchemy::after/);
  assert.match(css, /\.enemy\.cursed/);
  assert.match(css, /@keyframes enemy-hit-red/);
  assert.match(css, /@keyframes enemy-alchemy-dot/);
  assert.match(css, /@keyframes enemy-fate-dot/);
  assert.doesNotMatch(css, /\.tower-slot\.globalDot::after/);
  assert.match(css, /\.attack-royalFlush \.attack-impact\{border:4px double #ff8bea/);
  assert.match(css, /@keyframes tower-fire-kick/);
  assert.match(css, /@keyframes projectile-flight/);
  assert.match(css, /\.attack-fx\{inset:0;overflow:visible\}/);
  assert.match(css, /\.attack-straight \.attack-trace::after/);
  assert.match(css, /\.attack-triple \.attack-trace::after/);
  assert.match(css, /\.attack-fourKind \.attack-trace::after/);
  assert.match(css, /\.poker-card:has\(>span\.red-suit\)>b/);
  assert.match(css, /font-size:clamp\(16px,4\.8vw,22px\)/);
  assert.match(css, /--mobile-board:min\(calc\(100vw - 8px\),calc\(100svh/);
  assert.match(css, /grid-template-rows:36px 36px/);
  assert.match(page, /className="hand-glance"/);
  assert.match(page, /className="hand-wallet"/);
  assert.match(page, /className="gold-resource"/);
  assert.match(css, /--desktop-board:min\(700px,calc\(100dvh - 380px\)\)/);
  assert.match(css, /height:calc\(100dvh - 16px\);min-height:0;display:grid/);
  assert.match(css, /height:calc\(100svh - env\(safe-area-inset-top\) - env\(safe-area-inset-bottom\)\);min-height:0;display:flex;flex-direction:column;overflow:hidden/);
  assert.match(css, /\.pip-layout/);
  assert.match(css, /\.joker-art-black/);
  assert.match(css, /\.joker-art-color/);
  assert.match(css, /\.court-heart/);
  assert.match(css, /\.court-diamond/);
  assert.match(css, /\.court-club/);
  assert.match(css, /\.court-spade/);
  assert.match(css, /\.grid-slot\.priest-buffed/);
  assert.match(css, /priest-buffed:not\(\.priest-aura\)::after\{content:"✦"/);
  assert.match(css, /@keyframes priest-blessing/);
  assert.match(page, /className="boss-health"/);
  assert.match(page, /function confirmRareSale/);
  assert.match(page, /희귀 유닛입니다/);
  assert.match(page, /useState<1 \| 2 \| 3>\(1\)/);
  assert.match(page, /function cyclePlayback\(\)/);
  assert.match(page, /gameSpeed === 1 \? 2 : 3/);
  assert.match(page, /gameSpeed === 3/);
  assert.match(page, /setPlaybackPaused\(true\); setRunning\(false\)/);
  assert.match(page, /className="playback-control"/);
  assert.match(page, /playbackPaused \? "Ⅱ" : `\$\{gameSpeed\}×`/);
  assert.match(page, /!running && !playbackPaused/);
  assert.match(page, /elapsed \* gameSpeed/);
  assert.match(page, /earlyHpStart:\s*\.65/);
  assert.match(page, /earlyHpEnd:\s*\.8/);
  assert.match(page, /earlyEaseEnd:\s*40/);
  assert.match(page, /earlyBlendEnd:\s*55/);
  assert.match(page, /hardRamp \* earlyHpMultiplier\(wave\)/);
  assert.match(page, /baseInterval \* earlySpawnMultiplier\(wave\)/);
  assert.match(page, /enemy\.boss \? 20 : 1/);
  assert.match(page, /wave % 10 === 0 \? 1 : 60/);
  assert.match(page, /60 ENEMIES INCOMING/);
  assert.match(page, /bossWaveReleaseRef\.current = gameClockRef\.current \+ 60000/);
  assert.match(page, /NEXT \$\{formatTimer\(bossWaveHold\)\}/);
  assert.match(page, /gameClockRef\.current \+ 300000/);
  assert.match(page, /--boss-timer-label/);
  assert.match(page, /pointOnPath\(activeBoss\.progress\)/);
  assert.match(page, /--spawn-remaining-label/);
  assert.match(page, /Math\.max\(0, waveTarget - spawned\)/);
  assert.match(page, /BOSS TIME OVER/);
  assert.match(page, /completedBosses = Math\.floor\(\(wave - 1\) \/ 10\)/);
  assert.match(page, /강력한 단일 검기/);
  assert.match(css, /@keyframes alchemy-ground/);
  assert.match(css, /\.enemy\[title\*="이끼 슬라임"\]/);
  assert.match(css, /\.enemy\.boss-rank-10/);
  assert.match(css, /background-size:500% 400%/);
  assert.match(css, /\.language-cycle,\.playback-control button\{width:38px;height:38px/);
  assert.match(css, /grid-template-columns:minmax\(0,3fr\) minmax\(260px,1fr\)/);
  assert.match(css, /\.corner-controls\{position:fixed;top:auto;left:auto;right:8px;bottom:calc\(env\(safe-area-inset-bottom\) \+ 8px\)/);
  assert.match(css, /\.creator-credit\{left:auto;right:8px\}/);
  assert.match(css, /\.brand-copy span,[^\n]+\.creator-credit\{zoom:1\.1\}/);
  assert.match(css, /\.corner-controls\{position:static;grid-column:2;grid-row:4;justify-self:end/);
  assert.match(css, /\.poker-guide\{margin-top:70px\}/);
  assert.match(css, /\.brand-copy span\{font-size:10px/);
  assert.match(css, /\.battle-header>div\{min-width:0;display:flex/);
  assert.match(css, /\.spawn-gate::after\{font-size:11px/);
  assert.match(css, /\.section-title \.hand-wallet\{min-width:98px/);
  assert.match(css, /\.section-title \.hand-glance>span\{flex-direction:row/);
  assert.match(css, /\.hand-glance span small::after\{content:" \/"/);
  assert.match(css, /\.hand-glance span small\{[^\n]+font-size:13px/);
  assert.match(css, /left:auto!important; right:8px!important/);
  assert.match(css, /\.boss-health::before\{content:"BOSS " var\(--boss-timer-label/);
  assert.match(css, /\.playback-control output\.boss-time\{display:none\}/);
  assert.match(css, /\.spawn-gate::after\{content:var\(--spawn-remaining-label/);
  assert.match(css, /\.actions\{width:calc\(100% - 84px\);align-self:flex-start\}/);
  assert.match(page, /LOCALE_ORDER\.map\(language/);
  assert.match(page, /function cycleLocale\(\)/);
  assert.match(page, /!languageChosen/);
  assert.match(i18n, /ko:\[/);
  assert.match(i18n, /en:\[/);
  assert.match(i18n, /zh:\[/);
  assert.match(i18n, /ja:\[/);
  assert.match(i18n, /Seven-Card Summoning/);
  assert.match(i18n, /七张牌召唤/);
  assert.match(i18n, /セブンカード召喚/);
  assert.match(page, /createGameAudio/);
  assert.match(page, /playSound\("reroll"\)/);
  assert.match(page, /playSound\("upgrade"\)/);
  assert.match(audio, /class GameAudioController/);
  assert.match(audio, /playAttack\(category: AttackSound/);
  assert.match(audio, /maxVoices = 14/);
});
