import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(
    new Request("http://localhost/", { headers: { accept: "text/html" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

test("포커 랜덤 디펜스의 핵심 게임 화면을 렌더링한다", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);

  const html = await response.text();
  assert.match(html, /<title>포커 랜덤 디펜스<\/title>/);
  assert.match(html, /WAVE/);
  assert.match(html, /내 유닛/);
  assert.match(html, /전체 공격력/);
  assert.match(html, /전체 공격속도/);
  assert.match(html, /족보 확정 &amp; 소환/);
});

test("7장 손패와 모바일 전투 조작을 제공한다", async () => {
  const html = await (await render()).text();
  const pokerCards = html.match(/class="[^"]*poker-card[^"]*"/g) ?? [];
  assert.equal(pokerCards.length, 7);
  assert.match(html, /선택 카드 교체/);
  assert.match(html, /전체 손패 교체/);
  assert.match(html, /게임 시작/);
  assert.doesNotMatch(html, /52 \+ 2J/);
  assert.match(html, /200/);
});

test("현재 전투·연출·모바일 규칙을 고정한다", async () => {
  const [page, css, audio, i18n] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
    readFile(new URL("../app/game-audio.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/i18n.ts", import.meta.url), "utf8"),
  ]);

  assert.match(page, /POKER RANDOM DEFENSE/);
  assert.doesNotMatch(page, /FORTRESS OF FATE/);
  assert.match(page, /elf:\s*"\\uAD81\\uC218"/);
  assert.match(page, /const RANGE_PER_CELL = 100 \/ 12/);
  assert.match(page, /const PRIEST_BUFF_RANGE = RANGE_PER_CELL \* 3/);
  assert.match(page, /straight:\s*\{[\s\S]*?base:\s*\[15\.6,\s*RANGE_PER_CELL \* 5,\s*\.5\]/);
  assert.match(page, /flush:\s*\{[\s\S]*?base:\s*\[110,\s*RANGE_PER_CELL \* 2,\s*\.5\]/);
  assert.match(page, /fourKind:\s*\{[\s\S]*?base:\s*\[43\.5,\s*RANGE_PER_CELL \* 6,\s*1\.15\]/);
  assert.match(page, /royalFlush:\s*\{[\s\S]*?base:\s*\[140,\s*100,\s*1\.4\]/);
  assert.doesNotMatch(page, /rangeMult/);
  assert.match(page, /<= PRIEST_BUFF_RANGE/);
  assert.match(page, /markExpirations\.set\(target\.id,\s*now \+ 2000\)/);
  assert.match(page, /critical = Math\.random\(\) < \.5/);
  assert.match(page, /baseDamage \* \(critical \? 5 : 1\)/);
  assert.match(page, /case "straight": return "장거리 \+ 치명타확률 50% \+ 보스 추가피해 100%"/);
  assert.match(page, /case "pair": return "속사 \+ 2초간 받는 피해 20% 표식"/);
  assert.match(page, /tower\.category === "pair"[^}]+markExpirations\.set\(target\.id, now \+ 2000\)/);
  assert.match(page, /markedMultiplier = markExpirations\.has\(id\) \? 1\.2 : 1/);
  assert.match(page, /baseDamage \* \(critical \? 5 : 1\) \* \(target\.boss \? 2 : 1\)/);
  assert.match(page, /baseDamage \* \(target\.boss \? 2\.2 : 1\)/);
  assert.doesNotMatch(page, /장거리 \+ 피해 20% 표식/);
  assert.match(page, /const MAX_ATTACK_SPEED_LEVEL = 30/);
  assert.match(page, /attackMultiplier = 1 \+ attackLevel \* \.025/);
  assert.match(page, /attackSpeedMultiplier = 1 \+ attackSpeedLevel \* \.025/);
  assert.match(page, /attackLevel \* 2\.5\}%/);
  assert.match(page, /attackSpeedLevel \* 2\.5\}%/);
  assert.match(page, /attackSpeedLevel >= MAX_ATTACK_SPEED_LEVEL/);
  assert.match(page, /전체 공격속도는 LV\.30이 최대입니다/);
  assert.match(page, /lastAttackAtRef = useRef<Map<string, number>>/);
  assert.match(page, /attackInterval = 500 \/ Math\.max/);
  assert.match(page, /towerId: tower\.id,\s*expiresAt: now \+ 320/);
  assert.match(page, /attackFx\.some\(fx => fx\.towerId === tower\.id\) \? "attacking"/);
  assert.match(page, /fixedUtility = best\.category === "flush" \|\| best\.category === "fullHouse"/);
  assert.match(page, /triple:\s*\{[\s\S]*?base:\s*\[33,\s*RANGE_PER_CELL \* 5,\s*\.6\]/);
  assert.match(page, /flush:\s*\{[\s\S]*?base:\s*\[110,\s*RANGE_PER_CELL \* 2,\s*\.5\]/);
  assert.match(page, /fullHouse:\s*\{[\s\S]*?base:\s*\[21\.92,\s*RANGE_PER_CELL \* 4,\s*\.65\]/);
  assert.match(page, /className="inventory-selection"/);
  assert.match(page, /\{copy\.sell\} \{sellValue\(selectedInventoryUnit\)\}G/);
  assert.match(page, /className="field-unit-actions"/);
  assert.match(page, /function sellTower\(\)/);
  assert.match(page, /className=\{`hand-result summon-preview \$\{gameStarted/);
  assert.match(page, /className=\{`unit-dock/);
  assert.match(page, /className="summon-stats"/);
  assert.match(page, /setHand\(dealHand\(\)\)/);
  assert.match(page, /initialDealRef\.current = true; setHand\(dealHand\(\)\)/);
  assert.doesNotMatch(page, /saintPity|forcedSaintessHand|setSaintPity/);
  assert.match(page, /swapIndex = Math\.floor\(Math\.random\(\) \* \(index \+ 1\)\)/);
  assert.doesNotMatch(page, /sort\(\(\) => Math\.random\(\) - \.5\)/);
  assert.match(page, /const PIP_POSITIONS/);
  assert.match(page, /function cardCenter\(card: Card\)/);
  assert.match(page, /sprites\/royal-jester\.png/);
  assert.match(page, /sprites\/cards\/\$\{filename\}\.png/);
  assert.match(page, /court-\$\{card\.suit\}/);
  assert.match(page, /className="card-center"/);
  assert.match(page, /const cost = selected\.length \* 5 \* \(selectedRerollCount \+ 1\)/);
  assert.match(page, /setSelected\(selectedIndexes\.map\(index => next\[index\]\.id\)\)/);
  assert.match(page, /function redrawAll\(\)/);
  assert.match(page, /selectedRerollCount[^\n]+useState\(0\)/);
  assert.match(page, /setSelectedRerollCount\(v => v \+ 1\)/);
  assert.match(page, /setHand\(dealHand\(\)\);\s*setSelectedRerollCount\(0\);\s*setCooldown\(0\)/);
  assert.match(page, /selected\.length \* 5 \* \(selectedRerollCount \+ 1\)/);
  assert.match(page, /<em>×\{selectedRerollCount \+ 1\}<\/em>/);
  assert.match(page, /selected\.length \* 5 \* \(selectedRerollCount \+ 1\)\}G/);
  assert.doesNotMatch(page, /selectedRerollsLeft|reroll-exhausted|교체 불가/);
  assert.match(page, /wave === 1 && spawned === 0 \? baseCopy\.begin : baseCopy\.start/);
  assert.match(page, /if \(!running \|\| gameOver \|\| spawned >= waveTarget/);
  assert.match(page, /setGold\(v => v - 3\); setHand\(dealHand\(\)\)/);
  assert.match(page, /radius: 10,\s*expiresAt: now \+ 2000,[^}]+slow: \.5/);
  assert.match(page, /cursedHits\.add\(enemy\.id\)/);
  assert.match(page, /fourKind:[^\n]+base: \[43\.5, RANGE_PER_CELL \* 6, 1\.15\]/);
  assert.match(page, /straightFlush:[^\n]+base: \[224\.4, RANGE_PER_CELL \* 6, \.732\]/);
  assert.match(page, /category === "fourKind" \|\| category === "straightFlush"\)\s*return 3/);
  assert.match(page, /case "straightFlush": return "매우 강력한 단일 공격"/);
  assert.doesNotMatch(page, /if \(tower\.category === "straightFlush"\)/);
  assert.match(page, /royalFlush:[^\n]+base: \[140, 100, 1\.4\]/);
  assert.match(page, /setGold\(v => v \+ 2000\)/);
  assert.match(page, /spawnInterval: 600/);
  assert.match(page, /const VISIBLE_MAX_WAVE = 200/);
  assert.match(page, /const HIDDEN_WAVE = 201/);
  assert.match(page, /const MAX_WAVE = HIDDEN_WAVE/);
  assert.match(page, /const HIDDEN_BOSS_HP = 5000000/);
  assert.match(page, /const MAX_MONSTER_HP_MULTIPLIER = 2/);
  assert.match(page, /hidden-demon-lord\.png/);
  assert.match(page, /NORMAL_HP_DIFFICULTY_STEPS = \[\[10, 1\.3983\].+\[100, 4\.1578\].+\[200, 4\.9316\]\]/);
  assert.match(page, /Math\.pow\(1\.005, lateGrowthWaves\)/);
  assert.match(page, /BOSS_HP_BY_WAVE: Record<number, number> = \{ 10: 27000.+200: 2000000 \}/);
  const bossHpSource = page.match(/BOSS_HP_BY_WAVE: Record<number, number> = \{([^}]+)\}/)?.[1] ?? "";
  const bossHpValues = [...bossHpSource.matchAll(/\d+:\s*(\d+)/g)].map(match => Number(match[1]));
  assert.deepEqual(bossHpValues, [27000, 48000, 85000, 145000, 233000, 336000, 440000, 556000, 708000, 996000, 1080000, 1160000, 1250000, 1370000, 1500000, 1600000, 1700000, 1800000, 1900000, 2000000]);
  assert.ok(bossHpValues.every((hp, index) => index === 0 || hp > bossHpValues[index - 1]), "보스 체력은 매 보스 웨이브마다 증가해야 합니다");
  assert.equal(bossHpValues.at(-1), 2000000);
  assert.match(page, /function monsterPaletteForWave\(wave: number\)/);
  assert.match(page, /palette: monsterPalette/);
  assert.match(page, /function hpDifficultyForWave\(wave: number\)/);
  assert.match(page, /lowerMultiplier \+ \(upperMultiplier - lowerMultiplier\) \* progress/);
  assert.match(page, /function bossHpForWave\(wave: number\) \{ return wave === HIDDEN_WAVE \? HIDDEN_BOSS_HP : BOSS_HP_BY_WAVE\[wave\] \?\? BOSS_HP_BY_WAVE\[VISIBLE_MAX_WAVE\]; \}/);
  assert.match(page, /isHiddenWave \|\| wave % 10 === 0 \? 1 : 30/);
  assert.match(page, /hidden: hiddenSpawn/);
  assert.match(page, /e\.hidden \? "hidden-boss"/);
  assert.match(page, /saintesses\.length < 5/);
  assert.match(page, /saintess-ending-preview\/\?embedded=1&locale=\$\{locale\}/);
  assert.match(page, /demon-triumph-preview\/\?embedded=1&locale=\$\{locale\}/);
  assert.match(page, /title="ABSOLUTE TRIUMPH"/);
  assert.match(page, /return \{ damage: stackCount \* \.5, speed: 0 \}/);
  assert.match(page, /high: \[2, 3, 4\]/);
  assert.match(page, /pair: \[3, 5, 7\]/);
  assert.match(page, /twoPair: \[5, 8, 11\]/);
  assert.match(page, /fixedUtility = best\.category === "flush" \|\| best\.category === "fullHouse"/);
  assert.match(page, /\.slice\(0, 4\)/);
  assert.match(page, /투척 도끼 · 몬스터 4기 연쇄/);
  assert.match(page, /triple: \[10, 13, 15\]/);
  assert.match(page, /straight: \[15, 17, 20\]/);
  assert.match(page, /flush: \[20, 30, 40\]/);
  assert.match(page, /fullHouse: \[25, 35, 50\]/);
  assert.match(page, /fourKind: 100/);
  assert.match(page, /straightFlush: 200/);
  assert.match(page, /royalFlush: 350/);
  assert.match(page, /fiveKind: 500/);
  assert.match(page, /function spawnIntervalForWave\(_wave: number\) \{ return BALANCE\.spawnInterval; \}/);
  assert.doesNotMatch(page, /SPAWN_PRESSURE_CURVE|minSpawnInterval|baseInterval/);
  assert.match(page, /isPriestBuffed/);
  assert.match(page, /사제 버프 적용 중/);
  assert.match(page, /placeHint: selectedPlaced \? roleDescription\(selectedPlaced, locale\) : baseCopy\.placeHint/);
  assert.match(page, /\{term\(locale, result\.job\)\}/);
  assert.match(page, /\{term\(locale, result\.label\)\}/);
  assert.match(page, /\{term\(locale, result\.tierLabel\)\}/);
  assert.match(page, /\{term\(locale, unit\.job\)\}/);
  assert.match(page, /공격 사거리 4칸 · 버프 범위 3칸 내 사제 외 아군 공격력 \+50% · 공격속도 보정 없음 · 사제 수만큼 중복/);
  assert.match(page, /wave === VISIBLE_MAX_WAVE && enemies\.length > 0/);
  assert.match(page, /function priestBuffStacks\(tower: Tower, towers: Tower\[\]\)/);
  assert.match(page, /stackCount = priestBuffStacks\(tower, towers\)/);
  assert.match(page, /return \{ damage: stackCount \* \.5, speed: 0 \}/);
  assert.match(page, /setHiddenIntroActive\(true\)/);
  assert.match(page, /setTimeout\(\(\) => \{ setWave\(HIDDEN_WAVE\)/);
  assert.match(page, /1800/);
  assert.match(page, /if \(wave === HIDDEN_WAVE\)/);
  assert.match(page, /className="hidden-wave-intro"/);
  assert.match(i18n, /성녀 5기를 예비대에 모으는 선택에도 의미가 있습니다/);
  assert.match(i18n, /There is meaning in collecting five Saintesses/);
  assert.doesNotMatch(i18n, /201/);
  assert.match(page, /--selected-priest-stacks/);
  assert.match(css, /content:var\(--selected-priest-stacks/);
  assert.match(css, /\.field-unit-actions \{[^}]*width:min\(580px,96%\)[^}]*min-height:156px/);
  assert.match(css, /\.command-unit strong\{font-size:18px/);
  assert.match(css, /\.command-stats b\{font-size:16px/);
  assert.match(css, /\.game-frame:has\(\.field-unit-actions\)\{--mobile-command:92px\}/);
  assert.match(css, /--mobile-rail:52px/);
  assert.match(css, /\.battle-wrap \{[^}]*var\(--mobile-command\)[^}]*justify-items:start/);
  assert.match(css, /\.field-unit-actions \{ top:calc\(100% \+ 5px\); bottom:auto; left:0; transform:none/);
  assert.match(css, /\.corner-controls \{ position:fixed; top:calc\(env\(safe-area-inset-top\) \+ 53px\);[^}]*right:5px; bottom:auto; flex-direction:column/);
  assert.match(css, /\.alchemy-pool\s*\{/);
  assert.doesNotMatch(css, /\.tower-slot\.alchemy::after/);
  assert.match(css, /\.enemy\.cursed/);
  assert.match(css, /@keyframes enemy-hit-red/);
  assert.match(css, /@keyframes enemy-alchemy-dot/);
  assert.match(css, /@keyframes enemy-fate-dot/);
  assert.doesNotMatch(css, /\.tower-slot\.globalDot::after/);
  assert.match(css, /\.attack-royalFlush \.attack-impact\{border:4px double #ff8bea/);
  assert.match(css, /@keyframes tower-fire-kick/);
  assert.match(css, /@keyframes projectile-flight/);
  assert.match(css, /\.attack-fx\{inset:0;overflow:visible\}/);
  assert.match(css, /\.attack-straight \.attack-trace::after/);
  assert.match(css, /\.attack-triple \.attack-trace::after/);
  assert.match(css, /\.attack-fourKind \.attack-trace::after/);
  assert.match(css, /\.poker-card:has\(>span\.red-suit\)>b/);
  assert.match(css, /\.poker-card\.best \{[^}]*outline:3px solid #ffd966/);
  assert.match(css, /font-size:clamp\(16px,4\.8vw,22px\)/);
  assert.match(page, /className=\{`card-state \$\{state\}`\}/);
  assert.match(css, /\.card-slot\{min-width:0;min-height:0;display:grid;grid-template-rows:minmax\(0,1fr\) 22px/);
  assert.match(css, /\.card-state\{[^}]*font-size:10px/);
  assert.match(css, /\.poker-card>span small\{display:none\}/);
  assert.doesNotMatch(page, /className="spawn-gate">SPAWN/);
  assert.match(css, /--mobile-board:min\(calc\(100vw - var\(--mobile-rail\) - 8px\),calc\(100svh/);
  assert.match(css, /grid-template-rows:46px/);
  assert.match(css, /\.actions\{display:contents\}/);
  assert.match(css, /\.cards\{height:170px;grid-template-columns:repeat\(7,minmax\(0,105px\)\);justify-content:center/);
  assert.match(css, /\.actions \.primary-action\{right:12px;bottom:26px;[^}]*min-height:64px;font-size:16px/);
  assert.match(css, /\.tutorial-card\{width:min\(660px,86vw\);padding:40px/);
  assert.match(css, /\.tutorial-card>strong\{margin:22px 0 16px;font-size:32px/);
  assert.match(css, /\.army-upgrade span\{font-size:11px/);
  assert.match(css, /\.summon-copy>strong\{min-height:25px;font-size:16px/);
  assert.match(css, /\.poker-guide\[open\]\{height:min\(350px,calc\(100dvh - 580px\)\)/);
  assert.match(css, /\.poker-guide\[open\] \.guide-grid\{min-height:0;overflow-y:auto/);
  assert.match(css, /\.actions button\{min-height:46px;padding:3px 2px;font-size:12px/);
  assert.match(css, /\.actions \.selected-reroll-action\{grid-column:1;grid-row:1;display:flex;align-items:center;justify-content:center/);
  assert.match(page, /<b>3G<\/b>/);
  assert.match(css, /\.actions \.primary-action b\{display:none\}/);
  assert.match(css, /\.hand-panel:has\(\.cards\.cooling\) \.primary-action\{font-size:16px;line-height:1\}/);
  assert.match(css, /\.actions button\.pause,.game-frame:has\(\.playback-control button\.paused\) \.actions button\.start\{display:none\}/);
  assert.match(css, /\.actions button\.start\{position:fixed;z-index:25;top:calc\(env\(safe-area-inset-top\) \+ 72px/);
  assert.match(page, /className=\{`hand-glance \$\{gameStarted/);
  assert.match(page, /className="poker-card concealed"/);
  assert.match(page, /summon-preview \$\{gameStarted \? "" : "prestart-hidden"\}/);
  assert.match(page, /className="hand-wallet"/);
  assert.match(page, /className="wallet-coin"/);
  assert.doesNotMatch(page, /<small>GOLD :<\/small>/);
  assert.match(page, /className="summon-job"/);
  assert.match(page, /className="summon-hand-name"/);
  assert.match(css, /\.summon-path\{display:none\}/);
  assert.match(css, /\.summon-copy>strong\{[^}]*min-height:20px;[^}]*line-height:1\.35;[^}]*overflow:visible/);
  assert.match(page, /className="gold-resource"/);
  assert.doesNotMatch(page, /padStart\(3, "0"\)\} \/ 100/);
  assert.match(css, /--desktop-board:min\(730px,calc\(100dvh - 350px\)\)/);
  assert.match(css, /height:calc\(100dvh - 16px\);min-height:0;display:grid/);
  assert.match(css, /height:calc\(100svh - env\(safe-area-inset-top\) - env\(safe-area-inset-bottom\)\);min-height:0;display:flex;flex-direction:column;overflow:hidden/);
  assert.match(css, /\.pip-layout/);
  assert.match(css, /\.joker-art-black/);
  assert.match(css, /\.joker-art-color/);
  assert.match(css, /\.joker-art-invert/);
  assert.match(page, /joker\?: "black" \| "color" \| "invert"/);
  assert.match(page, /joker-invert/);
  assert.match(page, /sevenEntry = jokers\.length === 3/);
  assert.match(page, /best = \{ category: "sevenKind"/);
  assert.match(page, /result\.effect === "ending"/);
  assert.match(page, /setEndingActive\(true\)/);
  assert.match(page, /seven-card-ending-overlay/);
  assert.match(page, /seven-card-preview\/\?embedded=1/);
  assert.match(page, />PLAY AGAIN\?<\/button>/);
  assert.match(i18n, /endingReplay:"다시 플레이하기"/);
  assert.match(i18n, /endingReplay:"Play Again"/);
  assert.match(i18n, /endingReplay:"再玩一次"/);
  assert.match(i18n, /endingReplay:"もう一度プレイ"/);
  assert.match(css, /animation:ending-replay-in \.45s 4\.7s/);
  assert.match(page, /setCooldown\(5\)/);
  assert.doesNotMatch(page, /setCooldown\(10\)/);
  assert.match(css, /\.court-heart/);
  assert.match(css, /\.court-diamond/);
  assert.match(css, /\.court-club/);
  assert.match(css, /\.court-spade/);
  assert.match(css, /\.grid-slot\.priest-buffed/);
  assert.match(css, /priest-buffed:not\(\.priest-aura\)::after\{content:"✦"/);
  assert.match(css, /@keyframes priest-blessing/);
  assert.match(page, /className="boss-health"/);
  assert.match(page, /function confirmRareSale/);
  assert.match(page, /희귀 유닛입니다/);
  assert.match(page, /useState<1 \| 2 \| 3>\(1\)/);
  assert.match(page, /function cyclePlayback\(\)/);
  assert.match(page, /gameSpeed === 1 \? 2 : 3/);
  assert.match(page, /gameSpeed === 3/);
  assert.match(page, /setPlaybackPaused\(true\); setRunning\(false\)/);
  assert.match(page, /className="playback-control field-playback"/);
  assert.match(page, /playbackPaused \? "Ⅱ" : `\$\{gameSpeed\}×`/);
  assert.match(page, /!running && !playbackPaused/);
  assert.match(page, /elapsed \* gameSpeed/);
  assert.match(page, /cooldown <= 0 \|\| playbackPaused/);
  assert.match(page, /\[cooldown, gameSpeed, playbackPaused\]/);
  assert.match(page, /!selectedInventoryUnit \|\| playbackPaused/);
  assert.match(page, /!tower \|\| playbackPaused/);
  assert.match(css, /button\.paused\) \.field-unit-actions button\.sell/);
  assert.doesNotMatch(page, /earlyHpMultiplier|earlySpawnMultiplier|hardRamp/);
  assert.match(page, /enemy\.boss \? 20 : 1/);
  assert.match(page, /const APP_VERSION = "v0\.1002"/);
  assert.match(page, /\[gameStarted, setGameStarted\] = useState\(false\)/);
  assert.match(page, /setGameStarted\(true\)/);
  assert.match(page, /setGameStarted\(false\)/);
  assert.match(page, /function redraw\(\) \{ if \(!gameStarted \|\| cooldown > 0\)/);
  assert.match(page, /function redrawAll\(\) \{ if \(!gameStarted \|\| cooldown > 0\)/);
  assert.match(page, /function recruit\(\) \{ if \(!gameStarted \|\| cooldown > 0\)/);
  assert.match(page, /disabled=\{!gameStarted \|\| cooldown > 0\} onClick=\{recruit\}/);
  assert.doesNotMatch(page, /bossHpUnits|BOSS_HP_DIFFICULTY_STEPS/);
  assert.match(page, /hp = bossSpawn \? bossHpForWave\(wave\) : baseMonsterHp/);
  assert.match(page, /copy\.bossEquivalent/);
  assert.match(page, /Made by Arlandstrm with AI · \{APP_VERSION\}/);
  assert.match(page, /wave % 10 === 0 \? 1 : 30/);
  assert.doesNotMatch(page, /normalWaveHpCompensation/);
  assert.match(page, /function goldPerKillForWave\(_wave: number\) \{ return 1; \}/);
  assert.match(page, /bossSpawn \? 20 : 1/);
  assert.match(page, /30 ENEMIES INCOMING/);
  assert.match(page, /bossWaveReleaseRef\.current = gameClockRef\.current \+ 60000/);
  assert.match(page, /gameClockRef\.current \+ 180000/);
  assert.match(page, /bossDeadline\?: number/);
  assert.match(page, /bossDeadline: bossSpawn \? gameClockRef\.current \+ 180000 : undefined/);
  assert.match(page, /activeBosses\.map\(boss =>/);
  assert.match(page, /pointOnPath\(boss\.progress\)/);
  assert.match(page, /enemy\.bossDeadline <= now/);
  assert.match(page, /className="boss-timer"/);
  assert.doesNotMatch(page, /bossDeadlineRef|bossTimeLeft|--boss-timer-label/);
  assert.match(page, /className="spawn-counter"/);
  assert.match(page, /Math\.max\(0, waveTarget - spawned\)/);
  assert.match(page, /BOSS TIME OVER/);
  assert.match(page, /completedBosses = Math\.floor\(\(wave - 1\) \/ 10\)/);
  assert.match(page, /강력한 단일 검기 \+ 보스 120% 추가 피해/);
  assert.match(css, /@keyframes alchemy-ground/);
  assert.match(css, /\.enemy\[title\*="이끼 슬라임"\]/);
  assert.match(css, /\.enemy\.boss-rank-10/);
  assert.match(css, /background-size:500% 400%/);
  assert.match(css, /\.language-cycle,\.playback-control button\{width:38px;height:38px/);
  assert.match(css, /grid-template-columns:minmax\(0,3fr\) minmax\(260px,1fr\)/);
  assert.match(css, /\.corner-controls\{position:fixed;top:auto;left:auto;right:8px;bottom:calc\(env\(safe-area-inset-bottom\) \+ 8px\)/);
  assert.match(css, /\.creator-credit\{left:auto;right:8px\}/);
  assert.match(css, /\.brand-copy span,[^\n]+\.creator-credit\{zoom:1\.1\}/);
  assert.match(css, /\.corner-controls\{position:static;grid-column:2;grid-row:4;justify-self:end/);
  assert.match(css, /\.poker-guide\{margin-top:70px\}/);
  assert.match(css, /\.brand-copy span\{font-size:10px/);
  assert.match(css, /\.battle-header>div\{min-width:0;display:flex/);
  assert.doesNotMatch(page, /className="spawn-gate"/);
  assert.match(css, /\.section-title \.hand-wallet\{min-width:104px/);
  assert.match(css, /\.section-title \.hand-glance>span\{flex-direction:row/);
  assert.match(css, /\.hand-glance span b::after\{content:" \/"/);
  assert.match(css, /\.hand-glance span small::after\{content:" \/"/);
  assert.match(css, /\.hand-glance span small\{[^\n]+font-size:13px/);
  assert.match(css, /left:auto!important; right:8px!important/);
  assert.match(css, /\.boss-timer\{position:absolute/);
  assert.doesNotMatch(css, /--boss-timer-label|\.boss-health::before/);
  assert.match(css, /\.playback-control output\.boss-time\{display:none\}/);
  assert.match(css, /\.spawn-counter\{grid-area:progress/);
  assert.match(css, /\.actions\{width:100%;align-self:flex-start\}/);
  assert.doesNotMatch(css, /reroll-exhausted/);
  assert.match(page, /LOCALE_ORDER\.map\(language/);
  assert.doesNotMatch(page, /function cycleLocale\(\)/);
  assert.match(page, /!languageChosen/);
  assert.match(i18n, /ko:\[/);
  assert.match(i18n, /en:\[/);
  assert.match(i18n, /zh:\[/);
  assert.match(i18n, /ja:\[/);
  assert.match(i18n, /Seven-Card Summoning/);
  assert.match(i18n, /七张牌召唤/);
  assert.match(i18n, /セブンカード召喚/);
  assert.match(page, /createGameAudio/);
  assert.match(page, /playSound\("reroll"\)/);
  assert.match(page, /playSound\("upgrade"\)/);
  assert.match(audio, /class GameAudioController/);
  assert.match(audio, /playAttack\(category: AttackSound/);
  assert.match(audio, /maxVoices = 14/);
});
